### ISSUE TITLE
Unable to use layer in Lambda function

### ISSUE THREAD

**Issue by johnk-novu** [DataDog/datadog-lambda-layer-rb#6]
## Expected Behavior

The `arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Ruby:2` layer can be used in a Lambda function.

## Actual Behavior

An error message is presented:

> You are not authorized to perform: lambda:GetLayerVersion.

## Steps to Reproduce the Problem

  1. Create a lambda function
  1. Add `arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Ruby:2` layer
  1. Press "Save"

## Specifications

  - Datadog Lambda Layer version: `arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Ruby:2`
  - Ruby version: 2.5
  
## Stacktrace
  
  ```
  You are not authorized to perform: lambda:GetLayerVersion.
  ```

**Comment by pinkerton** [comment]
Hi @johnk-novu, thanks for the bug report! Which region is your Lambda function located in? Just want to make sure you're using a Layer region that matches that of your Lambda function.

**Comment by arich** [comment]
Hey @pinkerton! I'm working with @johnk-novu on this. The function is located in `us-east-1`.

**Comment by DarcyRaynerDD** [comment]
Hey @arich 
The correct lambda ARN is
```
arn:aws:lambda:us-east-1:464622532012:layer:Datadog-Ruby2-5:2
```
I think this was my bad, the release notes had an incorrect ARN. I've gone back and updated those.

**Comment by johnk-novu** [comment]
@DarcyRaynerDD that worked! Thanks so much.
